### ISSUE TITLE
Kostal Piko an einem Multiplus 2 GX meldet Permission denied

### ISSUE THREAD

**Issue by Heini1985** [schenlap/venus_kostal_pico#10]
Hallo zusammen.
ich habe einen Multiplus GX im Einsatz.
ich habe alles nach Anleitung gemacht aber er führt den Script nicht aus (siehe Bild)
![image](https://user-images.githubusercontent.com/76739980/219942438-221fcb96-b65e-4752-9b92-ada564e0b410.png)

Die Ordner Struktur sieht wie folgt aus:
![image](https://user-images.githubusercontent.com/76739980/219942525-f8d704c0-4ac0-4377-942d-589fbe544807.png)

Remote Konsole auch nach Neustart kein kostal:
![image](https://user-images.githubusercontent.com/76739980/219942584-ac3ff989-87e8-42cb-956c-a5ee5b76f7ac.png)

Vielleich kann mir einer helfen?

Viele Grüße

Heini1985

**Comment by schenlap** [comment]
Du musst das script start_kostal_pico ausführbar machen. Aktuell hat es nur die Rechte -rw-r--r--
mach mal 
`chmod +x /data/venus_kostal_pico/start_kostal_pico`

**Comment by Heini1985** [comment]
Danke für den TIP.

ich habe es jetzt ausgeführt und bekomme das in ssh ausgegeben:

![image](https://user-images.githubusercontent.com/76739980/221968004-4c49684d-92ec-4cef-aaa5-686135be7ef4.png)

mein Remote Console sieht jetz so aus:

![image](https://user-images.githubusercontent.com/76739980/221968157-63a61cf6-2c65-4f92-9185-e093bdeac727.png)

der PV Wechselrichter ist jetzt natürlich aus weil keine Sonne mehr vorhanden ist.
ich schaue morgen nach ob es funktioniert hat

VG Heini1985

**Comment by Heini1985** [comment]
Hallo ich habe heute nochmal versucht er ist angelegt aber bekommt keine werte.
sieht wie folgt aus:
![image](https://user-images.githubusercontent.com/76739980/222211952-601d8dd2-b379-4eb8-8082-0a6832d342e4.png)
![image](https://user-images.githubusercontent.com/76739980/222212062-23f435f2-e31c-493d-9bd8-4b1dca11c393.png)
![image](https://user-images.githubusercontent.com/76739980/222212191-606b62f0-1873-4153-81eb-bc6c02850d44.png)

und ich habe herausgefunden das ich wahrscheinlich Vers 3 benutzen muss, weil wenn ich die adresse http:<IP>/api/dxs.json?dxsEntries=67109120 eingebe bekomme ich das als Ausgabe:

![image](https://user-images.githubusercontent.com/76739980/222212797-afb963f8-f2fc-4ea8-acf8-ffbf7a40dd1e.png)

Im ssh habe ich jetzt folgende Fehlermeldung:

![image](https://user-images.githubusercontent.com/76739980/222211838-8d10fd5d-0b83-4e94-be16-b9595a77361b.png)

VG

Hein1985

**Comment by schenlap** [comment]
Scheint so als ob das script 2 mal läuft, kann das sein?

**Comment by Heini1985** [comment]
kann sein

**Comment by Heini1985** [comment]
kann man das löschen und von vorne Beginen?

**Comment by schenlap** [comment]
Mit ps aux /oder eventuell auch nur ps siehst du alle laufenden Prozesse. Mit kill und der Prozessnummer kannst du den beenden. Er wird irgendwas mit "python kostal.py" oder start_kostal_pico heißen. Die Prozessnummer müsste in der 2ten Zeile angezeigt werden.

**Comment by Heini1985** [comment]
ich habe die Zeilen zu kostal pico aus  /data/rc.local gelöscht --> dann neu gestartet-->pico war weg.
Dann habe ich alles nochmal nach Anleitung gemach:

# Install
If setting up root access (preferable with ssh key), create a folder in data and add start script
ssh int venus
```
mkdir /data/venus_kostal_pico
echo -e '#!/bin/bash' >> /data/rc.local
echo '(cd /data/venus_kostal_pico/ && ./start_kostal_pico)' >> /data/rc.local
chmod +x /data/rc.local
exit

in ssh sah es dann so aus.

![image](https://user-images.githubusercontent.com/76739980/222221103-18dfab8a-7f8d-4c1f-af26-bb4d7ef47d29.png)


Und jetzt scheint es zu funktionieren er hat zu mindestens den Zähler ausgelesen zu habe und die Spannungen sind jetzt auf 0V weil kein Sonne mehr das ist

![image](https://user-images.githubusercontent.com/76739980/222220864-d956e51b-a37b-4039-b6e9-59833bc35788.png)

Ich schaue mal morgen od er daten liefert wenn ja dann ist es top 

Danke für die Hilfe

VG

Heini1985

**Comment by Heini1985** [comment]
ich habe die Zeilen zu kostal pico aus /data/rc.local gelöscht --> dann neu gestartet-->pico war weg.
Dann habe ich alles nochmal nach Anleitung gemach:

Install
If setting up root access (preferable with ssh key), create a folder in data and add start script
ssh int venus

mkdir /data/venus_kostal_pico
echo -e '#!/bin/bash' >> /data/rc.local
echo '(cd /data/venus_kostal_pico/ && ./start_kostal_pico)' >> /data/rc.local
chmod +x /data/rc.local
exit

in ssh sah es dann so aus.

![image](https://user-images.githubusercontent.com/76739980/222221602-82a71756-b789-4f54-965d-17ad1487560d.png)

Und jetzt scheint es zu funktionieren er hat zu mindestens den Zähler ausgelesen zu habe und die Spannungen sind jetzt auf 0V weil kein Sonne mehr das ist

![image](https://user-images.githubusercontent.com/76739980/222221719-fd33733f-fcca-4ad5-8885-d8760551a1ba.png)


Ich schaue mal morgen ob er daten liefert wenn ja dann ist es top 

Danke für die Hilfe

VG

Heini1985

**Comment by schenlap** [comment]
Super. Eigentlich würde ich erwarten dass die Spannungen trotzdem angezeigt werden, am Netz liegt die Spannung ja an. Bei mir mit Version1 ist es jedenfalls so. Ich bin bespannt. Ich bin morgen vermutlich nicht erreichbar, am Freitag dann wieder.

**Comment by Heini1985** [comment]
Es hat funktioniert.

Danke für die Hilfe.

Du kannst das Thema schießen.
