### ISSUE TITLE
Script hangs at request 

### ISSUE THREAD

**Issue by jangatzke** [schenlap/venus_kostal_pico#6]
For my Kostal Piko 3 the script did not run stable. After some time it stopped processing because it hung at response = requests.get(... forever. The timeout given in the script did not help. After some research this seems to bei a common problem with the Python requests library. This is solved by adding a general socket timeout by adding these two lines:
import socket
.
.
.
socket.setdefaulttimeout(10)

Now my problems are gone. Hope this helps somebody else!

**Comment by Hans0612** [comment]
Hello, can you tell me more precisely in which file and where you inserted these lines?
Have the same problem, the query hangs after 1-2 hours and an incorrect value is continuously displayed
