### ISSUE TITLE
only L1 power values is transmitted

### ISSUE THREAD

**Issue by gnagflow80** [schenlap/venus_kostal_pico#8]
Hi, is it normal, that only L1 power value is transmitted to the gx portal?

![kostal_venus](https://user-images.githubusercontent.com/81044114/205599063-649b3a3b-6ea4-4846-9a1b-cce71b0a142f.jpg)

**Comment by gnagflow80** [comment]
I use Kostal 4.2 (oldest version --> set v1 in kostal.ini file

**Comment by schenlap** [comment]
Yes, when generating very low power the inverter only uses L1. With more power it will use L2 and L3.
